---
title: "Bare Essential Code to Run Massive Experiment"
author: "Akshay Jaggi, Sandy Napel"
date: "07/14/2020"
output: pdf_document
---

```{r setup, include=FALSE}
library(caret)
library(dplyr)
library(mRMRe)
library(xgboost)
library(ada)
library(irr)
source("ml_battery_script.R")
```


```{r import_data}
# Upload the Full Final Data Set, these files are not provided to users
dat_full1  = read.csv("rcc_final1.csv")[-1]
dat_full2  = read.csv("rcc_final2.csv")[-1]
true_names = read.csv("true_feature_names.csv",header=FALSE)
```

```{r cleanup}
colnames(dat_full1) = true_names$V1
colnames(dat_full2) = true_names$V1
dat_full1 = dat_full1[-1:-2]
dat_full2 = dat_full2[-1:-2]
labels = dat_full1$labels
```

```{r drop_labels}
# ONLY RUN THIS ONCE BEWARE
dat_full1  = subset(dat_full1,select = -c(labels))
dat_full2  = subset(dat_full2,select = -c(labels))
dat_full1  = dat_full1[-c(916:920,1700:1704)]
dat_full2  = dat_full2[-c(916:920,1700:1704)]
```

```{r extract_subset}
dat_subset1 = dat_full1[grep("intensity|texture", colnames(dat_full1))]
dat_subset2 = dat_full2[grep("intensity|texture", colnames(dat_full2))]
```

# Further Data Cleaning
Addressing remaining cleaning problems
```{r read data, include = FALSE}
data_subset_c1 = data.frame(dat_subset1)
data_subset_c1["Label"] = as.factor(labels)
levels(data_subset_c1$Label)[levels(data_subset_c1$Label) == "0"] = "X0"
levels(data_subset_c1$Label)[levels(data_subset_c1$Label) == "1"] = "X1"
colnames(data_subset_c1) = str_replace_all(colnames(data_subset_c1), "[^[:alnum:]]", ".")
data_subset_c2  =  data.frame(dat_subset2)
data_subset_c2["Label"] = as.factor(labels)
levels(data_subset_c2$Label)[levels(data_subset_c2$Label) == "0"] = "X0"
levels(data_subset_c2$Label)[levels(data_subset_c2$Label) == "1"] = "X1"
colnames(data_subset_c2) = str_replace_all(colnames(data_subset_c2), "[^[:alnum:]]", ".")
```


Note: This code is run after "data_cleaning.Rmd"
This code will use the data frames generated by that code

# Simultaneous Comparison of ICC CutOff, mRMR Filter, Model Type
Given n icc cutoffs, m mRMR cutoffs, and t model types, 
we'll test nxmxt combinations of these parameters and plot that comparison. 

```{r set parameters for simul comp}
parameters_big = list(
  "cutoffs" = c(0.7,0.75,0.8,0.85,0.9,0.95,0.99),
  "features" = c(5,10,15,20,50),
  "selections" = c("mRMR"), 
  "classifiers" = c("ada", "xgbLinear","xgbTree","rf"))
```

```{r run the simul comp modeling}
n_validations = 2
seed = 1
all_model_results = 
  ml_battery_overhead_icc(data_subset_c1, data_subset_c2,
                          "Label", n_validations, parameters_big, seed)
```

